@baseURL = http://localhost:8080

# Index
GET {{baseURL}}

###

# Create
POST {{baseURL}}/new HTTP/1.1
Content-Type: application/x-www-form-urlencoded

text=タイトル
&status=New

###

# Detail
GET {{baseURL}}/detail/0

###

# Update
POST {{baseURL}}/update/0
Content-Type: application/json

{
    "text": "update",
    "status": "update123"
}

###

# Delete Check
GET {{baseURL}}/delete_check/0

###

# Delete
POST {{baseURL}}/delete/0

###

# Delete All
POST {{baseURL}}/delete_all

###

# Ping
GET {{baseURL}}/ping

###

# JSON
GET {{baseURL}}/json/hoge